apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/js-lib.version: "latest"
    spec:
      containers:
        - name: sample-node-app
          image: wwongpai/sample-node-noapm-new:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DD_ENV
              value: "prod"
            - name: DD_SERVICE
              value: "my_nodejs_app"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP